conky.config = {
    alignment = 'top_left',
    background = false,
    border_width = 1,
    default_color = 'white',
    double_buffer = true,
    draw_borders = false,
    font = 'DejaVu Sans Mono:size=15',
    gap_x = 35,
    gap_y = 60,
    minimum_height = 7,
    minimum_width = 250,
    no_buffers = true,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    update_interval = 1.0,
    use_xft = true,
}

conky.text = [[
${alignc}${color #ff33f4}${font DejaVu Sans Mono:size=45}${time %H:%M}${font}
${voffset 10}${alignc}${color #ff66f7}${font DejaVu Sans Mono:size=18}${time %Y / %m / %d (%a)}${font}
$hr
${color #ff33f4}User:$color ${execi 3600 whoami}
${color #ff33f4}NixOS:$color ${execi 3600 nixos-version --print-id --short}
${color #ff33f4}Kernel:$color $kernel
${color #ff33f4}Machine:$color ThinkPad E14 Gen4
${color #ff33f4}Architecture:$color $machine
]]
